displayName=Log Adviser
author=SFranciscoSouza
description=Suggests collection log activities personalized to your log
tags=collection,log,clog,adviser,advisor
plugins=com.logadviser.LogAdviserPlugin
build=standard
